version: '3'
services:
  core:
    container_name: core
    image: core
    build: ./marker-core
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  ui:
    container_name: ui
    image: ui
    build: ./marker-client
    ports:
      - "3000:3000"
    depends_on:
      - core
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    image: nginx
    build: ./.nginx
    depends_on:
      - core
      - ui
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork: